# Generated by Django 5.2.5 on 2025-08-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0002_candidature_email_candidature_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='cv_url',
            field=models.URLField(blank=True, help_text='URL du CV original', max_length=500),
        ),
        migrations.AddField(
            model_name='candidature',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text="Formations (ex: [{'school': 'Université X', 'degree': 'Master Info', 'duration': '2016-2018'}])"),
        ),
        migrations.AddField(
            model_name='candidature',
            name='experiences',
            field=models.JSONField(blank=True, default=list, help_text="Expériences professionnelles (ex: [{'company': 'TechCorp', 'position': 'Dev Senior', 'duration': '2020-2024', 'description': '...'}])"),
        ),
        migrations.AddField(
            model_name='candidature',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text="Centres d'intérêt (liste de strings)"),
        ),
        migrations.AddField(
            model_name='candidature',
            name='summary',
            field=models.TextField(blank=True, help_text='Résumé complet du CV'),
        ),
    ]
